<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0992b0eb9f959e91380d446f033d687f
{
    public static $files = array (
        '49a1299791c25c6fd83542c6fedacddd' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v4p11.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stonewall\\SwgDirectory\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stonewall\\SwgDirectory\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0992b0eb9f959e91380d446f033d687f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0992b0eb9f959e91380d446f033d687f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0992b0eb9f959e91380d446f033d687f::$classMap;

        }, null, ClassLoader::class);
    }
}
